### ISSUE TITLE
respect .npmrc from the calling process

### ISSUE THREAD

**Issue by hiebj** [team-griffin/install-self-peers#4]
My team needs to be able to install `peerDependencies` during development.

We prefer your tool, as it is the only package we have found that does not require global installation. However, it does not respect the `.npmrc` from the `cwd` of the calling process - that is, when you `spawn()` the `yarn install`, it's running from the current working directory of your npm module (within `node_modules`), not ours. Your tool cannot find our private Artifactory server without the `.npmrc`.

**In short, the installation fails** if packages sourced from a private repository are included in `peerDependencies`.

I'd like to suggest that you accept a parameter for the `cwd` from which to `spawn()` the new `install` process, or else derive the caller's origin directory from `process.cwd()`, potentially with a flag. That would make `npm` or `yarn` able to respect the caller's NPM config.

For example, [cli.js#L32](https://github.com/team-griffin/install-self-peers/blob/master/lib/cli.js#L32) becomes:
```
    commandConfig.args,
    { stdio: 'inherit', cwd: process.cwd() }
)
```

If you don't want to make this change, we can fork your project to add this feature and submit a pull request. Otherwise, the alternative is to fork your project and maintain it locally. It's up to you, but until Yarn or NPM implement an `install --peers` option, it's either that or a bunch of shell hackery.

---------

Incidentally, I think that **`postinstall` is the wrong [lifecycle event](https://docs.npmjs.com/misc/scripts)** to use for your script.

`postinstall` is called after a package is installed by a dependent, meaning that if I put `install-self-peers` in a `postinstall`, any dependent of my package is forced to install my `peerDependencies` locally whenever my package is installed. That's not ideal.

**The `prepare` lifecycle event works a little better**. It is only run:

1. just after a local `npm install`
2. just before a local `npm publish`

As such, `prepare` works as intended, doesn't affect dependents and has minimal impact on `publish` runs - it shouldn't change the output and doesn't slow it down much.

**You might also suggest a non-lifecycle `script`** that a developer must call explicitly, such as `npm run install-peers`.

This is just a suggestion for your docs. We're using `prepare` in our code and it works great (other than the `.npmrc` issue above).

**In other words:**
```
where:
B is my module
=> is a dependency or devDependency
-> is a peerDependency

A => B -> C
[postinstall]: A.install yields both B and C
[  prepare  ]: A.install yields only B, unless A => C
```

**Comment by jshthornton** [comment]
I don't think this request is very sound. If you were to call `yarn install` from a directory outside of your project directory it would also complain. The fact that your `.npmrc` isn't being found sounds more like a problem with expected usage than recommended usage.

That is to say that this project assumes that you will be calling it at the root directory of your project. Which is recommended.

**Comment by hiebj** [comment]
Okay, then it's possible that I'm doing something wrong. I am calling it from the root level of my project. I have `install-self-peers -- --ignore-scripts` in my `prepare` script, and it's being triggered when I run `yarn install` from the root level. I've attached output from my CLI when running from a totally clean install (no `node_modules/` or `yarn.lock`). It's looking for my private packages from the `npm` registry, and seems to be ignoring the `.npmrc` which indicates it should be connecting to our private mirror.

The private package in question that it's failing to find is `style` which is our theme package. As you can see, `yarn install` itself is able to find one of our other private packages, `react-webpack` (which is a `devDependency`) with no problem - so the base `yarn install` is correctly finding our `.npmrc` and talking to the local mirror.

It's only the second step from `install-self-peers` that is not working.

Is there something else I'm missing?

```
USMAC2750JHIEB:project-name jon.hieb$ rm -rf node_modules/
USMAC2750JHIEB:project-name jon.hieb$ rm yarn.lock
USMAC2750JHIEB:project-name jon.hieb$ yarn install
yarn install v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "chai-enzyme@0.7.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
warning "enzyme@2.8.2" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x".
warning "react-dom@15.6.0" has unmet peer dependency "react@^15.6.0-rc.1".
warning "react-element-to-jsx-string@5.0.7" has unmet peer dependency "react@^0.14.8 || ^15.0.1".
warning "react-webpack@1.3.5" has unmet peer dependency "react@^15.6.0".
warning "redbox-react@1.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
$ install-self-peers -- --ignore-scripts
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
error Couldn't find package "style" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
✨  Done in 17.94s.
USMAC2750JHIEB:package-name jon.hieb$
```

**Comment by hiebj** [comment]
I think what is happening is that since your package actually lives in my `node_modules/`, the `cwd` when your script executes is the root directory of *your* package, not mine. In fact, I can demonstrate this by adding a `console.log()` statement. A call to `process.cwd()` returns the intended root - *my* project root - but logging `__dirname` outputs the directory of your package:

```
USMAC2750JHIEB:package-name jon.hieb$ yarn run prepare
yarn run v0.24.5
$ install-self-peers -- --ignore-scripts
process.cwd(): /Users/jon.hieb/development/package-name
__dirname: /Users/jon.hieb/development/package-name/node_modules/@team-griffin/install-self-peers/lib
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
error Couldn't find package "style" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
✨  Done in 2.58s.
```

**Comment by hiebj** [comment]
For clarity, I added those logging statements on lines 28 and 29 of `cli.js`:

![screen shot 2017-06-14 at 2 45 14 pm](https://user-images.githubusercontent.com/4262078/27153819-1f12d4a0-5110-11e7-9881-976ed9e5cfde.png)

**Comment by hiebj** [comment]
Just for kicks, I also tested it with your command in the `postinstall` step. Same problem:

```
USMAC2750JHIEB:project-name jon.hieb$ yarn install
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ install-self-peers -- --ignore-scripts
process.cwd(): /Users/jon.hieb/development/project-name
__dirname: /Users/jon.hieb/development/project-name/node_modules/@team-griffin/install-self-peers/lib
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
error Couldn't find package "style" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
✨  Done in 2.31s.
```

**Comment by hiebj** [comment]
Surprisingly, even changing the command like so does not work:
```
install-self-peers -- --userconfig /Users/jon.hieb/development/project-name/.npmrc --ignore-scripts
```

The log output indicates that it's actually ignoring the package config because it detects that it is the same as the given user config:

```
2 info using npm@5.0.3
3 info using node@v7.2.0
4 verbose config Skipping project config: /Users/jon.hieb/development/package-name/.npmrc. (matches userconfig)
5 verbose npm-session 48fe8dd8250d73b1
6 silly install loadCurrentTree
```

I've tested to make sure that a standard `yarn add -P style` works. It does:

```
USMAC2750JHIEB:package-name jon.hieb$ yarn add -P style
yarn add v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-webpack@1.3.5" has unmet peer dependency "react@^15.6.0".
warning "chai-enzyme@0.7.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
warning "enzyme@2.8.2" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x".
warning "react-dom@15.6.0" has unmet peer dependency "react@^15.6.0-rc.1".
warning "react-element-to-jsx-string@5.0.7" has unmet peer dependency "react@^0.14.8 || ^15.0.1".
warning "redbox-react@1.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
```

**Comment by hiebj** [comment]
I can't get the `process.cwd()` trick to work either. I swear I tested it last night, but it's not working now. So, right now nothing works. I simply can't get the child process to pick up the `--registry`, whether it's from a CLI option or `.npmrc`.

**Comment by hiebj** [comment]
Wow. I have finally found a solution. If I change the command to this, it works:

```
install-self-peers --npm -- --ignore-scripts --registry http://my.artifactory.com/artifactory/api/npm/npm-virtual
```

It works in `npm@5`, too, with the `--no-save` flag (which is kind of surprising, since `npm@5` hardly ever works).

`yarn` does not work; `yarn` [does not appear](https://yarnpkg.com/en/docs/cli/install) to accept a `registry` param from the CLI. I tried it anyway, it doesn't work.

If you are able to connect to a local `npm` mirror using `.npmrc`, I'd love to see proof. If you can't make it work either, you might want to explicitly document this workaround.

**Comment by jshthornton** [comment]
@hiebj I will be setting up a private registry here soon. So I will investigate the issue once I can replicate it.
